# Generated by Django 4.2.27 on 2026-01-31 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workouts", "0016_alter_ridedetail_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("vibe", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommender_profile",
                        to="workouts.instructor",
                    ),
                ),
            ],
            options={
                "ordering": ["instructor__name"],
            },
        ),
    ]
