# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructorprofile",
            options={
                "ordering": ["instructor__name"],
                "permissions": [("can_use_recommender", "Can use Recommender")],
            },
        ),
    ]
