# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_alter_instructorprofile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructorprofile",
            options={"ordering": ["instructor__name"]},
        ),
    ]
