# Generated by Django 6.0.1 on 2026-02-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RideSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        db_index=True,
                        help_text="Peloton class ID (e.g., from API or extracted from class URL)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current sync status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if sync failed (e.g., class not found on Peloton, API error)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this queue entry was created"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this class was successfully synced (status='synced' or 'failed')",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Sync Queue",
                "verbose_name_plural": "Ride Sync Queues",
                "ordering": ["status", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_ridesy_status_612dc3_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_ridesy_status_8e19da_idx",
                    ),
                ],
            },
        ),
    ]
