# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "require_user_activation",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, new user accounts require admin activation before they can log in. Disable this when out of development mode to allow automatic registration.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
                "permissions": [("can_use_core", "Can use Core")],
            },
        ),
    ]
