# Generated by Django 4.2.27 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sitesettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="annual_challenge_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Peloton Annual Challenge ID to track for the current year (e.g., 67bfab351b6f4e239ed17aadf28c006e).",
                max_length=64,
            ),
        ),
    ]
