# Generated by Django 4.2.27 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_annual_challenge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="annual_challenge_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display name for the current annual challenge (e.g., Annual Challenge 2026).",
                max_length=120,
            ),
        ),
    ]
