# Generated by Django 6.0.1 on 2026-01-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kegel", "Kegel"),
                            ("mobility", "Mobility"),
                            ("yoga", "Yoga"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=120)),
                ("key_cue", models.TextField()),
                ("reps_hold", models.CharField(max_length=60)),
                ("primary_use", models.CharField(blank=True, max_length=120)),
                ("video_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanTemplateDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ]
                    ),
                ),
                ("peloton_focus", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="plans.plantemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week"],
                "unique_together": {("template", "day_of_week")},
            },
        ),
    ]
