# Generated by Django 4.2.27 on 2026-01-20 22:52

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image showing the exercise",
                null=True,
                upload_to=plans.models.exercise_image_path,
            ),
        ),
    ]
