# Generated by Django 4.2.27 on 2026-01-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_exercise_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantemplateday",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ]
            ),
        ),
    ]
