# Generated by Django 4.2.27 on 2026-01-26 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0003_alter_plantemplateday_day_of_week"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecapShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year for this recap")),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique token for the share link",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this share link is active"
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this recap has been viewed",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this recap was viewed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recap_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="plans_recap_token_649cc8_idx"),
                    models.Index(
                        fields=["user", "year"], name="plans_recap_user_id_952d79_idx"
                    ),
                ],
                "unique_together": {("user", "year")},
            },
        ),
    ]
