# Generated by Django 4.2.27 on 2026-01-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0004_recapshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecapCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year for this recap cache")),
                ("daily_activities", models.JSONField(blank=True, default=dict)),
                ("daily_calories", models.JSONField(blank=True, default=dict)),
                ("daily_power", models.JSONField(blank=True, default=dict)),
                ("distance_stats", models.JSONField(blank=True, default=dict)),
                ("total_hours", models.JSONField(blank=True, default=dict)),
                ("streaks", models.JSONField(blank=True, default=dict)),
                ("rest_days", models.JSONField(blank=True, default=dict)),
                ("start_times", models.JSONField(blank=True, default=dict)),
                ("activity_count", models.JSONField(blank=True, default=dict)),
                ("training_load", models.JSONField(blank=True, default=dict)),
                ("personal_records", models.JSONField(blank=True, default=dict)),
                ("consistency_metrics", models.JSONField(blank=True, default=dict)),
                ("summary_stats", models.JSONField(blank=True, default=dict)),
                ("top_instructors", models.JSONField(blank=True, default=dict)),
                ("top_songs", models.JSONField(blank=True, default=dict)),
                ("duration_distribution", models.JSONField(blank=True, default=dict)),
                ("peak_performance", models.JSONField(blank=True, default=dict)),
                ("elevation_stats", models.JSONField(blank=True, default=dict)),
                ("weekday_patterns", models.JSONField(blank=True, default=dict)),
                ("workout_type_breakdown", models.JSONField(blank=True, default=dict)),
                ("progress_over_time", models.JSONField(blank=True, default=dict)),
                (
                    "best_workouts_by_discipline",
                    models.JSONField(blank=True, default=dict),
                ),
                ("calorie_efficiency", models.JSONField(blank=True, default=dict)),
                (
                    "average_metrics_breakdown",
                    models.JSONField(blank=True, default=dict),
                ),
                ("monthly_comparison", models.JSONField(blank=True, default=dict)),
                ("favorite_class_types", models.JSONField(blank=True, default=dict)),
                ("time_of_day_patterns", models.JSONField(blank=True, default=dict)),
                ("year_over_year", models.JSONField(blank=True, default=dict)),
                ("challenge_participation", models.JSONField(blank=True, default=dict)),
                ("intensity_zones", models.JSONField(blank=True, default=dict)),
                ("distance_milestones", models.JSONField(blank=True, default=dict)),
                ("consistency_score", models.JSONField(blank=True, default=dict)),
                ("heart_rate_zones", models.JSONField(blank=True, default=dict)),
                (
                    "cadence_resistance_trends",
                    models.JSONField(blank=True, default=dict),
                ),
                ("yearly_calendar", models.JSONField(blank=True, default=dict)),
                ("total_workouts_count", models.IntegerField(default=0)),
                (
                    "last_workout_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recap_caches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "year"], name="plans_recap_user_id_bf7950_idx"
                    )
                ],
                "unique_together": {("user", "year")},
            },
        ),
    ]
