# Generated by Django 4.2.27 on 2026-01-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_recapcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="recapcache",
            name="last_regenerated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time user manually regenerated this cache",
                null=True,
            ),
        ),
    ]
