# Generated by Django 4.2.27 on 2026-02-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_recapcache_last_regenerated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("yoga", "Yoga"),
                    ("pilates", "Pilates"),
                    ("breathwork", "Breathwork"),
                    ("mobility", "Mobility"),
                ],
                max_length=20,
            ),
        ),
    ]
