# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0007_update_exercise_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantemplateday",
            options={
                "ordering": ["day_of_week"],
                "permissions": [("can_use_plans", "Can use Plans")],
            },
        ),
    ]
