# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_alter_plantemplateday_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantemplateday",
            options={"ordering": ["day_of_week"]},
        ),
    ]
