# Generated by Django 4.2.27 on 2026-01-23 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FTPEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ftp_value", models.IntegerField(help_text="FTP value in watts")),
                (
                    "recorded_date",
                    models.DateField(help_text="Date when FTP was recorded"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Added"),
                            ("ftp_test", "FTP Test"),
                            ("ai_detected", "AI Detected"),
                        ],
                        default="manual",
                        help_text="How the FTP was determined",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this FTP is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ftp_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_ftpentry",
                "ordering": ["-recorded_date", "-created_at"],
            },
        ),
    ]
