# Generated by Django 4.2.27 on 2026-01-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_ftpentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pace_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pace value in minutes per mile",
                        max_digits=5,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("running", "Running"), ("walking", "Walking")],
                        help_text="Running or Walking",
                        max_length=10,
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(help_text="Date when pace was recorded"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually Added"),
                            ("pace_test", "Pace Test"),
                            ("ai_detected", "AI Detected"),
                        ],
                        default="manual",
                        help_text="How the pace was determined",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this pace is currently active for this activity type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pace_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_paceentry",
                "ordering": ["-recorded_date", "-created_at"],
                "unique_together": {
                    ("user", "activity_type", "recorded_date", "source")
                },
            },
        ),
    ]
