# Generated by Django 4.2.27 on 2026-01-23 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_paceentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(help_text="Pace level (1-10)")),
                (
                    "recorded_date",
                    models.DateField(help_text="Date when this pace level was set"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this pace level"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pace_levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_pacelevel",
                "ordering": ["-recorded_date", "-level"],
                "unique_together": {("user", "level", "recorded_date")},
            },
        ),
        migrations.CreateModel(
            name="PaceBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("recovery", "Recovery"),
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("hard", "Hard"),
                            ("very_hard", "Very Hard"),
                            ("max", "Max"),
                        ],
                        help_text="Pace zone name",
                        max_length=20,
                    ),
                ),
                (
                    "min_mph",
                    models.DecimalField(
                        decimal_places=1, help_text="Minimum speed in MPH", max_digits=4
                    ),
                ),
                (
                    "max_mph",
                    models.DecimalField(
                        decimal_places=1, help_text="Maximum speed in MPH", max_digits=4
                    ),
                ),
                (
                    "min_pace",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum pace in min/mile",
                        max_digits=5,
                    ),
                ),
                (
                    "max_pace",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum pace in min/mile",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of this pace zone",
                        max_length=255,
                    ),
                ),
                (
                    "pace_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="accounts.pacelevel",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_paceband",
                "ordering": ["zone"],
                "unique_together": {("pace_level", "zone")},
            },
        ),
    ]
