# Generated by Django 4.2.27 on 2026-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_pacelevel_paceband"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paceentry",
            name="pace_value",
        ),
        migrations.AddField(
            model_name="paceentry",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (4, "Level 4"),
                    (5, "Level 5"),
                    (6, "Level 6"),
                    (7, "Level 7"),
                    (8, "Level 8"),
                    (9, "Level 9"),
                    (10, "Level 10"),
                ],
                default=5,
                help_text="Pace level (1-10)",
            ),
        ),
        migrations.AlterField(
            model_name="paceentry",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this pace level is currently active for this activity type",
            ),
        ),
        migrations.AlterField(
            model_name="paceentry",
            name="recorded_date",
            field=models.DateField(help_text="Date when pace level was recorded"),
        ),
        migrations.AlterField(
            model_name="paceentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manually Added"),
                    ("pace_test", "Pace Test"),
                    ("ai_detected", "AI Detected"),
                ],
                default="manual",
                help_text="How the pace level was determined",
                max_length=20,
            ),
        ),
    ]
