# Generated by Django 4.2.27 on 2026-01-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_paceentry_pace_value_paceentry_level_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pacelevel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pacelevel",
            name="activity_type",
            field=models.CharField(
                choices=[("running", "Running"), ("walking", "Walking")],
                default="running",
                help_text="Running or Walking",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="paceband",
            name="zone",
            field=models.CharField(help_text="Pace zone name", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="pacelevel",
            unique_together={("user", "activity_type", "level", "recorded_date")},
        ),
    ]
