# Generated by Django 4.2.27 on 2026-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_pacelevel_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="peloton_leaderboard_name",
            field=models.CharField(
                blank=True,
                help_text="Peloton leaderboard name (synced from Peloton account)",
                max_length=255,
                null=True,
            ),
        ),
    ]
