# Generated by Django 6.0.1 on 2026-01-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_peloton_leaderboard_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="peloton_last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time Peloton data was synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_calories",
            field=models.IntegerField(
                blank=True,
                help_text="Total calories burned from all Peloton workouts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_distance",
            field=models.FloatField(
                blank=True,
                help_text="Total distance in miles from all Peloton workouts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_output",
            field=models.BigIntegerField(
                blank=True,
                help_text="Total output in kilojoules from all Peloton workouts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_pedaling_duration",
            field=models.IntegerField(
                blank=True, help_text="Total pedaling duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_workouts",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of Peloton workouts completed",
                null=True,
            ),
        ),
    ]
