# Generated by Django 6.0.1 on 2026-01-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_peloton_last_synced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="peloton_best_weekly_streak",
            field=models.IntegerField(
                blank=True, help_text="Best weekly workout streak achieved", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_current_daily_streak",
            field=models.IntegerField(
                blank=True, help_text="Current daily workout streak", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_current_weekly_streak",
            field=models.IntegerField(
                blank=True, help_text="Current weekly workout streak", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_achievements",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of Peloton achievements earned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_non_pedaling_metric_workouts",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of Peloton workouts without pedaling metrics (meditation, strength, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="peloton_total_pedaling_metric_workouts",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of Peloton workouts with pedaling metrics (cycling, etc.)",
                null=True,
            ),
        ),
    ]
