# Generated by Django 6.0.1 on 2026-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_peloton_best_weekly_streak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="peloton_workout_counts",
            field=models.JSONField(
                blank=True,
                help_text="Breakdown of Peloton workouts by type (slug -> count)",
                null=True,
            ),
        ),
    ]
