# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_profile_peloton_workout_counts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("can_use_accounts", "Can use Accounts")]},
        ),
    ]
