# Generated by Django 4.2.27 on 2026-02-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingWizard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.IntegerField(
                        choices=[
                            (1, "Stage 1"),
                            (2, "Stage 2"),
                            (3, "Stage 3"),
                            (4, "Stage 4"),
                            (5, "Stage 5"),
                            (6, "Stage 6"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "completed_stages",
                    models.JSONField(
                        default=list, help_text="List of completed stage numbers (1-6)"
                    ),
                ),
                (
                    "stage_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Intermediate form data for resuming wizard",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When wizard was fully completed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_wizard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Wizard",
                "verbose_name_plural": "Onboarding Wizards",
                "db_table": "accounts_onboardingwizard",
            },
        ),
    ]
