# Generated by Django 6.0.1 on 2026-02-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_onboardingwizard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaceBand",
        ),
    ]
