"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-j+-w&y$2r==-=40grf=vad!h2s51&%q98u!#*_l00y6^h6$sca"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# CSRF trusted origins for HTTPS
CSRF_TRUSTED_ORIGINS = [
    "https://chase.haresign.dev",
    "https://app.chasethehare.com",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
     # django-allauth
     "django.contrib.sites",
     "allauth",
     "allauth.account",

    # Core services (shared across apps)
    "core",
    
    # Project apps
    "accounts",
    "plans",
    "annual_challenge",
    "recommender",
    "tracker",
    "challenges",
    "classes",  # Peloton class catalog/library
    "workouts",  # Workout history & tracking
    "peloton",
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication Backend
# Using allauth's backend which handles email-based authentication
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Login/Logout redirects
LOGIN_REDIRECT_URL = "core:dashboard"
LOGOUT_REDIRECT_URL = "core:landing"

# Django Sites Framework (required by allauth)
SITE_ID = 1

# django-allauth Configuration (using new API)
ACCOUNT_UNIQUE_EMAIL = True  # Email must be unique
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # Tell allauth there's no username field
ACCOUNT_LOGIN_METHODS = {'email'}  # Email-only authentication
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Email and password fields
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
ACCOUNT_SIGNUP_REDIRECT_URL = LOGIN_REDIRECT_URL
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Disable rate limiting to avoid IP detection issues
ACCOUNT_LOGIN_RATE_LIMIT = None
ACCOUNT_SIGNUP_RATE_LIMIT = None

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.OnboardingRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES[0]["DIRS"] = [BASE_DIR / "templates"]

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Onboarding wizard redirect exceptions
ONBOARDING_EXEMPT_URLNAMES = {
    "login",
    "logout",
    "account_logout",  # allauth logout
    "account_signup",  # allauth signup/registration
    "register",
    "account_inactive",
    "wizard_redirect",
    "wizard_stage_1",
    "wizard_stage_2",
    "wizard_stage_3",
    "wizard_stage_4",
    "wizard_stage_4_backdated_ftp",
    "wizard_stage_4_backdated_pace",
    "wizard_stage_5",
    "wizard_stage_5_backdated",
    "wizard_stage_6",
    "wizard_restart",
    "landing",
}
ONBOARDING_EXEMPT_PATH_PREFIXES = [
    "/admin/",
    f"/{STATIC_URL.lstrip('/')}",
    f"/{MEDIA_URL.lstrip('/')}",
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Increase field limit for admin bulk operations (e.g., deleting many workouts)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'peloton': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Process one task at a time for better memory usage
CELERY_TASK_ACKS_LATE = True  # Acknowledge tasks after completion

# Remember-me and secure session cookie settings
REMEMBER_ME_DAYS = int(os.environ.get('REMEMBER_ME_DAYS', '30'))
# Default session cookie age remains, but we enforce secure cookie flags for safety
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
