# Generated by Django 6.0.1 on 2026-01-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peloton", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelotonconnection",
            name="_encrypted_bearer_token",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="_encrypted_refresh_token",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
