# Generated by Django 6.0.1 on 2026-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peloton", "0002_pelotonconnection__encrypted_bearer_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelotonconnection",
            name="sync_cooldown_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When sync can be run again (60 min cooldown)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="sync_in_progress",
            field=models.BooleanField(
                default=False, help_text="Whether a sync is currently in progress"
            ),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="sync_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the current sync started", null=True
            ),
        ),
    ]
