# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peloton", "0003_add_sync_status_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pelotonconnection",
            options={
                "permissions": [("can_use_peloton", "Can use Peloton")],
                "verbose_name": "Peloton Connection",
                "verbose_name_plural": "Peloton Connections",
            },
        ),
    ]
