# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peloton", "0004_alter_pelotonconnection_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pelotonconnection",
            options={
                "verbose_name": "Peloton Connection",
                "verbose_name_plural": "Peloton Connections",
            },
        ),
    ]
