# Generated by Django 4.2.27 on 2026-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peloton", "0005_alter_pelotonconnection_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pelotonconnection",
            name="following_cooldown_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When following can be fetched again (60 min cooldown)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="following_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Peloton user IDs that this user follows",
            ),
        ),
        migrations.AddField(
            model_name="pelotonconnection",
            name="following_last_sync_at",
            field=models.DateTimeField(
                blank=True, help_text="When following IDs were last fetched", null=True
            ),
        ),
    ]
