# Generated by Django 4.2.27 on 2026-02-04 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualChallengeProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("challenge_id", models.CharField(db_index=True, max_length=64)),
                ("minutes_ytd", models.IntegerField(blank=True, null=True)),
                ("metric_display_value", models.CharField(blank=True, max_length=32)),
                ("metric_display_unit", models.CharField(blank=True, max_length=16)),
                ("has_joined", models.BooleanField(default=False)),
                ("challenge_status", models.CharField(blank=True, max_length=32)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="annual_challenge_progress", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-last_synced_at", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="annualchallengeprogress",
            constraint=models.UniqueConstraint(fields=("user", "challenge_id"), name="unique_annual_challenge_progress"),
        ),
    ]
