# Generated by Django 4.2.27 on 2026-01-22 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "peloton_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Workout duration in minutes"),
                ),
                (
                    "peloton_id",
                    models.CharField(
                        blank=True,
                        help_text="Peloton workout ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "peloton_url",
                    models.URLField(
                        blank=True, help_text="Link to workout on Peloton", null=True
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        help_text="Date when workout was originally recorded/created on Peloton"
                    ),
                ),
                (
                    "completed_date",
                    models.DateField(help_text="Date when user completed this workout"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this workout was synced from Peloton",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this workout was synced"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty_rating",
                    models.FloatField(
                        blank=True, help_text="Workout difficulty rating", null=True
                    ),
                ),
                (
                    "total_ratings",
                    models.IntegerField(default=0, help_text="Total number of ratings"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workouts",
                        to="workouts.instructor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_date", "-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier (e.g., 'bicycle', 'running', 'yoga')",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tss",
                    models.FloatField(
                        blank=True, help_text="Training Stress Score", null=True
                    ),
                ),
                (
                    "tss_target",
                    models.FloatField(blank=True, help_text="Target TSS", null=True),
                ),
                (
                    "avg_output",
                    models.FloatField(
                        blank=True, help_text="Average output in watts", null=True
                    ),
                ),
                (
                    "total_output",
                    models.FloatField(
                        blank=True, help_text="Total output in kilojoules", null=True
                    ),
                ),
                (
                    "max_output",
                    models.FloatField(
                        blank=True, help_text="Maximum output in watts", null=True
                    ),
                ),
                (
                    "avg_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in mph", null=True
                    ),
                ),
                (
                    "max_speed",
                    models.FloatField(
                        blank=True, help_text="Maximum speed in mph", null=True
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance in miles", null=True
                    ),
                ),
                (
                    "avg_heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Average heart rate in bpm", null=True
                    ),
                ),
                (
                    "max_heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Maximum heart rate in bpm", null=True
                    ),
                ),
                (
                    "avg_cadence",
                    models.IntegerField(
                        blank=True, help_text="Average cadence in rpm", null=True
                    ),
                ),
                (
                    "max_cadence",
                    models.IntegerField(
                        blank=True, help_text="Maximum cadence in rpm", null=True
                    ),
                ),
                (
                    "avg_resistance",
                    models.FloatField(
                        blank=True, help_text="Average resistance", null=True
                    ),
                ),
                (
                    "max_resistance",
                    models.FloatField(
                        blank=True, help_text="Maximum resistance", null=True
                    ),
                ),
                (
                    "total_calories",
                    models.IntegerField(
                        blank=True, help_text="Total calories burned", null=True
                    ),
                ),
                (
                    "workout",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout Metrics",
            },
        ),
        migrations.AddField(
            model_name="workout",
            name="workout_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workouts",
                to="workouts.workouttype",
            ),
        ),
        migrations.CreateModel(
            name="PelotonConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("peloton_username", models.CharField(blank=True, max_length=200)),
                ("peloton_user_id", models.CharField(blank=True, max_length=100)),
                (
                    "api_token",
                    models.TextField(blank=True, help_text="Peloton API token"),
                ),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="Peloton API refresh token"),
                ),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic syncing"
                    ),
                ),
                (
                    "sync_frequency_hours",
                    models.IntegerField(
                        default=24, help_text="Hours between automatic syncs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peloton_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Peloton Connection",
                "verbose_name_plural": "Peloton Connections",
            },
        ),
        migrations.CreateModel(
            name="WorkoutPerformanceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.IntegerField(help_text="Time in seconds from workout start"),
                ),
                (
                    "output",
                    models.FloatField(
                        blank=True,
                        help_text="Output in watts at this timestamp",
                        null=True,
                    ),
                ),
                (
                    "cadence",
                    models.IntegerField(
                        blank=True,
                        help_text="Cadence in rpm at this timestamp",
                        null=True,
                    ),
                ),
                (
                    "resistance",
                    models.FloatField(
                        blank=True, help_text="Resistance at this timestamp", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Speed in mph at this timestamp",
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True,
                        help_text="Heart rate in bpm at this timestamp",
                        null=True,
                    ),
                ),
                (
                    "power_zone",
                    models.IntegerField(
                        blank=True,
                        help_text="Power zone (1-7) at this timestamp",
                        null=True,
                    ),
                ),
                (
                    "intensity_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("recovery", "Recovery"),
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("hard", "Hard"),
                            ("very_hard", "Very Hard"),
                            ("max", "Max"),
                        ],
                        help_text="Intensity zone at this timestamp",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="workouts.workout",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workout Performance Data",
                "ordering": ["workout", "timestamp"],
                "indexes": [
                    models.Index(
                        fields=["workout", "timestamp"],
                        name="workouts_wo_workout_1eced3_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["user", "-completed_date"],
                name="workouts_wo_user_id_dc9ce1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["workout_type"], name="workouts_wo_workout_449788_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["instructor"], name="workouts_wo_instruc_96740b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["peloton_id"], name="workouts_wo_peloton_cfc112_idx"
            ),
        ),
    ]
