# Generated by Django 6.0.1 on 2026-01-24 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peloton_ride_id",
                    models.CharField(
                        db_index=True,
                        help_text="Peloton ride/class ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_seconds",
                    models.IntegerField(help_text="Class duration in seconds"),
                ),
                (
                    "fitness_discipline",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'cycling', 'yoga', 'running'",
                        max_length=50,
                    ),
                ),
                (
                    "fitness_discipline_display_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Cycling', 'Yoga', 'Running'",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty_rating_avg",
                    models.FloatField(
                        blank=True, help_text="Average difficulty rating", null=True
                    ),
                ),
                (
                    "difficulty_rating_count",
                    models.IntegerField(
                        default=0, help_text="Number of difficulty ratings"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'beginner', 'intermediate', 'advanced'",
                        max_length=50,
                    ),
                ),
                ("overall_estimate", models.FloatField(blank=True, null=True)),
                ("difficulty_estimate", models.FloatField(blank=True, null=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Class thumbnail/image URL", null=True
                    ),
                ),
                (
                    "home_peloton_id",
                    models.CharField(
                        blank=True, help_text="Home Peloton ID", max_length=100
                    ),
                ),
                (
                    "original_air_time",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Unix timestamp when class originally aired",
                        null=True,
                    ),
                ),
                (
                    "scheduled_start_time",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Unix timestamp of scheduled start",
                        null=True,
                    ),
                ),
                (
                    "created_at_timestamp",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Unix timestamp when class was created",
                        null=True,
                    ),
                ),
                (
                    "class_type_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="List of class type IDs"
                    ),
                ),
                (
                    "equipment_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="List of equipment IDs"
                    ),
                ),
                (
                    "equipment_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of equipment tag objects",
                    ),
                ),
                (
                    "content_format",
                    models.CharField(
                        blank=True, help_text="e.g., 'video', 'audio'", max_length=50
                    ),
                ),
                (
                    "content_provider",
                    models.CharField(
                        blank=True, help_text="e.g., 'peloton'", max_length=50
                    ),
                ),
                ("has_closed_captions", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this ride detail was first synced",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this ride detail was synced"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride Detail",
                "verbose_name_plural": "Ride Details",
                "ordering": ["-original_air_time", "title"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tss",
                    models.FloatField(
                        blank=True, help_text="Training Stress Score", null=True
                    ),
                ),
                (
                    "tss_target",
                    models.FloatField(blank=True, help_text="Target TSS", null=True),
                ),
                (
                    "avg_output",
                    models.FloatField(
                        blank=True, help_text="Average output in watts", null=True
                    ),
                ),
                (
                    "total_output",
                    models.FloatField(
                        blank=True, help_text="Total output in kilojoules", null=True
                    ),
                ),
                (
                    "max_output",
                    models.FloatField(
                        blank=True, help_text="Maximum output in watts", null=True
                    ),
                ),
                (
                    "avg_speed",
                    models.FloatField(
                        blank=True, help_text="Average speed in mph", null=True
                    ),
                ),
                (
                    "max_speed",
                    models.FloatField(
                        blank=True, help_text="Maximum speed in mph", null=True
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance in miles", null=True
                    ),
                ),
                (
                    "avg_heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Average heart rate in bpm", null=True
                    ),
                ),
                (
                    "max_heart_rate",
                    models.IntegerField(
                        blank=True, help_text="Maximum heart rate in bpm", null=True
                    ),
                ),
                (
                    "avg_cadence",
                    models.IntegerField(
                        blank=True, help_text="Average cadence in rpm", null=True
                    ),
                ),
                (
                    "max_cadence",
                    models.IntegerField(
                        blank=True, help_text="Maximum cadence in rpm", null=True
                    ),
                ),
                (
                    "avg_resistance",
                    models.FloatField(
                        blank=True, help_text="Average resistance", null=True
                    ),
                ),
                (
                    "max_resistance",
                    models.FloatField(
                        blank=True, help_text="Maximum resistance", null=True
                    ),
                ),
                (
                    "total_calories",
                    models.IntegerField(
                        blank=True, help_text="Total calories burned", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout Details",
                "verbose_name_plural": "Workout Details",
            },
        ),
        migrations.RemoveField(
            model_name="workoutmetrics",
            name="workout",
        ),
        migrations.RemoveIndex(
            model_name="workout",
            name="workouts_wo_workout_449788_idx",
        ),
        migrations.RemoveIndex(
            model_name="workout",
            name="workouts_wo_instruc_96740b_idx",
        ),
        migrations.RemoveIndex(
            model_name="workout",
            name="workouts_wo_peloton_cfc112_idx",
        ),
        migrations.AddField(
            model_name="workout",
            name="peloton_workout_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Peloton workout ID (unique per workout instance)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True, help_text="Workout duration in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_workouts",
                to="workouts.instructor",
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="peloton_id",
            field=models.CharField(
                blank=True,
                help_text="Legacy: Peloton workout ID (use peloton_workout_id)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="workout",
            name="workout_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_workouts",
                to="workouts.workouttype",
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ride_details",
                to="workouts.instructor",
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="workout_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ride_details",
                to="workouts.workouttype",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="ride_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="The class/ride this workout is based on",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workouts",
                to="workouts.ridedetail",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["ride_detail"], name="workouts_wo_ride_de_24b419_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["peloton_workout_id"], name="workouts_wo_peloton_50687c_idx"
            ),
        ),
        migrations.AddField(
            model_name="workoutdetails",
            name="workout",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="workouts.workout",
            ),
        ),
        migrations.DeleteModel(
            name="WorkoutMetrics",
        ),
        migrations.AddIndex(
            model_name="ridedetail",
            index=models.Index(
                fields=["peloton_ride_id"], name="workouts_ri_peloton_f810d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridedetail",
            index=models.Index(
                fields=["workout_type"], name="workouts_ri_workout_b8d7d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridedetail",
            index=models.Index(
                fields=["instructor"], name="workouts_ri_instruc_2b80ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ridedetail",
            index=models.Index(
                fields=["fitness_discipline"], name="workouts_ri_fitness_baddff_idx"
            ),
        ),
    ]
