# Generated by Django 6.0.1 on 2026-01-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_add_ride_detail_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetail",
            name="peloton_class_url",
            field=models.URLField(
                blank=True, help_text="Link to class on Peloton website", null=True
            ),
        ),
    ]
