# Generated by Django 6.0.1 on 2026-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_add_peloton_class_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridedetail",
            name="difficulty_level",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'beginner', 'intermediate', 'advanced'",
                max_length=50,
                null=True,
            ),
        ),
    ]
