# Generated by Django 6.0.1 on 2026-01-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_allow_null_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="bio",
            field=models.TextField(blank=True, help_text="Instructor biography"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time this instructor was synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="location",
            field=models.CharField(
                blank=True, help_text="Instructor location", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="synced_at",
            field=models.DateTimeField(
                blank=True, help_text="When this instructor was first synced", null=True
            ),
        ),
        migrations.AddField(
            model_name="instructor",
            name="username",
            field=models.CharField(
                blank=True, help_text="Peloton username", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="image_url",
            field=models.URLField(blank=True, help_text="Profile image URL", null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="peloton_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="instructor",
            index=models.Index(
                fields=["peloton_id"], name="workouts_in_peloton_6ea18b_idx"
            ),
        ),
    ]
