# Generated by Django 6.0.1 on 2026-01-25 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_add_instructor_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="description",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="difficulty_rating",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="peloton_id",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="title",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="total_ratings",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="workout_type",
        ),
        migrations.AlterField(
            model_name="workout",
            name="ride_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="The class/ride this workout is based on. All class details come from here via SQL joins.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workouts",
                to="workouts.ridedetail",
            ),
        ),
    ]
