# Generated by Django 6.0.1 on 2026-01-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_remove_duplicate_fields_from_workout"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetail",
            name="is_power_zone_class",
            field=models.BooleanField(
                default=False, help_text="Whether this is a Power Zone class"
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="pace_target_type",
            field=models.CharField(
                blank=True,
                help_text="Pace target type for tread runs (e.g., 'pace_target', 'pace_zone')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="target_class_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Target class metrics (e.g., total_expected_output)",
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="target_metrics_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Target metrics data structure with segments, zones, and ranges",
            ),
        ),
    ]
