# Generated by Django 4.2.27 on 2026-01-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_add_target_metrics_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peloton_playlist_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Peloton playlist ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "songs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of songs with full details (title, artists, album, timing, etc.)",
                    ),
                ),
                (
                    "top_artists",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top artists featured in this playlist",
                    ),
                ),
                (
                    "top_albums",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top albums featured in this playlist",
                    ),
                ),
                (
                    "stream_id",
                    models.CharField(
                        blank=True,
                        help_text="Stream ID for playlist",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stream_url",
                    models.URLField(
                        blank=True, help_text="Stream URL for playlist", null=True
                    ),
                ),
                (
                    "is_top_artists_shown",
                    models.BooleanField(
                        default=False, help_text="Whether to show top artists"
                    ),
                ),
                (
                    "is_playlist_shown",
                    models.BooleanField(
                        default=False, help_text="Whether to show playlist"
                    ),
                ),
                (
                    "is_in_class_music_shown",
                    models.BooleanField(
                        default=False, help_text="Whether to show in-class music"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this playlist was first synced",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this playlist was synced"
                    ),
                ),
                (
                    "ride_detail",
                    models.OneToOneField(
                        help_text="The class/ride this playlist belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist",
                        to="workouts.ridedetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "ordering": ["-synced_at"],
                "indexes": [
                    models.Index(
                        fields=["peloton_playlist_id"],
                        name="workouts_pl_peloton_0d06e2_idx",
                    ),
                    models.Index(
                        fields=["ride_detail"], name="workouts_pl_ride_de_3b200b_idx"
                    ),
                ],
            },
        ),
    ]
