# Generated by Django 4.2.27 on 2026-01-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0008_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetail",
            name="segments_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Segments structure with segment_list containing Warm Up, Main, Cool Down sections and subsegments",
            ),
        ),
    ]
