# Generated by Django 4.2.27 on 2026-01-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0009_ridedetail_segments_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetail",
            name="class_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("power_zone", "Power Zone"),
                    ("climb", "Climb"),
                    ("intervals", "Intervals"),
                    ("progression", "Progression"),
                    ("low_impact", "Low Impact"),
                    ("beginner", "Beginner"),
                    ("groove", "Groove"),
                    ("pro_cyclist", "Pro Cyclist"),
                    ("music", "Music"),
                    ("theme", "Theme"),
                    ("live_dj", "Live DJ"),
                    ("peloton_studio_original", "Peloton Studio Original"),
                    ("pace_target", "Pace Target"),
                    ("speed", "Speed"),
                    ("endurance", "Endurance"),
                    ("walk_run", "Walk + Run"),
                    ("form_drills", "Form & Drills"),
                    ("power_walk", "Power Walk"),
                    ("hiking", "Hiking"),
                    ("warm_up", "Warm Up"),
                    ("cool_down", "Cool Down"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Type of class (Power Zone, Pace Target, Climb, Intervals, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ridedetail",
            name="is_power_zone_class",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a Power Zone class (deprecated - use class_type instead)",
            ),
        ),
    ]
