# Generated by Django 4.2.27 on 2026-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0011_add_strength_yoga_meditation_class_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "peloton_id",
                    models.CharField(
                        db_index=True,
                        help_text="Peloton class type ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Power Zone', 'Climb')",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, help_text="URL-friendly slug", max_length=200
                    ),
                ),
                (
                    "fitness_discipline",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., 'cycling', 'running', 'strength', 'yoga'",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata from Peloton API",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this class type was first synced",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this class type was synced"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this class type is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Type",
                "verbose_name_plural": "Class Types",
                "ordering": ["fitness_discipline", "name"],
                "indexes": [
                    models.Index(
                        fields=["peloton_id"], name="workouts_cl_peloton_dbc8ab_idx"
                    ),
                    models.Index(
                        fields=["fitness_discipline"],
                        name="workouts_cl_fitness_2973ca_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="workouts_cl_is_acti_6ae50d_idx"
                    ),
                ],
            },
        ),
    ]
