# Generated by Django 4.2.27 on 2026-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0012_add_class_type_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ridedetail",
            name="home_peloton_id",
            field=models.CharField(
                blank=True, help_text="Home Peloton ID", max_length=100, null=True
            ),
        ),
    ]
