# Generated by Django 4.2.27 on 2026-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0013_allow_null_home_peloton_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ridedetail",
            options={
                "ordering": ["-original_air_time", "title"],
                "permissions": [
                    (
                        "manage_spin_ups",
                        "Can manage spin-ups for power zone classes (full access)",
                    ),
                    ("edit_spin_ups", "Can edit spin-ups for power zone classes"),
                ],
                "verbose_name": "Ride Detail",
                "verbose_name_plural": "Ride Details",
            },
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="spin_ups_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=3,
                help_text="Number of spin-ups in warm-up section (pyramids Zone 1 to top of Zone 3)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="spin_ups_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                help_text="Duration of each spin-up in seconds",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ridedetail",
            name="spin_ups_gap_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                help_text="Gap/recovery time between spin-ups in seconds",
                null=True,
            ),
        ),
    ]
