# Generated by Django 4.2.27 on 2026-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0014_add_spin_ups_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridedetail",
            name="spin_ups_start_time_offset",
            field=models.PositiveIntegerField(
                blank=True,
                default=170,
                help_text="Start time offset in seconds for spin-ups (e.g., 170 for 2:50)",
                null=True,
            ),
        ),
    ]
