# Generated by Django 6.0.1 on 2026-01-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0015_add_spin_ups_start_time_offset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ridedetail",
            options={
                "ordering": ["-original_air_time", "title"],
                "verbose_name": "Ride Detail",
                "verbose_name_plural": "Ride Details",
            },
        ),
        migrations.RemoveField(
            model_name="ridedetail",
            name="spin_ups_count",
        ),
        migrations.RemoveField(
            model_name="ridedetail",
            name="spin_ups_duration_seconds",
        ),
        migrations.RemoveField(
            model_name="ridedetail",
            name="spin_ups_gap_seconds",
        ),
        migrations.RemoveField(
            model_name="ridedetail",
            name="spin_ups_start_time_offset",
        ),
    ]
