# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0016_alter_ridedetail_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classtype",
            options={
                "ordering": ["fitness_discipline", "name"],
                "permissions": [("can_use_workouts", "Can use Workouts")],
                "verbose_name": "Class Type",
                "verbose_name_plural": "Class Types",
            },
        ),
    ]
