# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0017_alter_classtype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classtype",
            options={
                "ordering": ["fitness_discipline", "name"],
                "verbose_name": "Class Type",
                "verbose_name_plural": "Class Types",
            },
        ),
    ]
