# Generated by Django 6.0.1 on 2026-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0018_alter_classtype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutdetails",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="Actual workout duration in seconds (from performance data)",
                null=True,
            ),
        ),
    ]
