# Generated by Django 4.2.27 on 2026-02-08 00:13

from django.db import migrations, models
from datetime import datetime, time
from django.utils import timezone
try:
    from zoneinfo import ZoneInfo
except ImportError:
    from backports.zoneinfo import ZoneInfo


def populate_completed_at(apps, schema_editor):
    Workout = apps.get_model("workouts", "Workout")
    ET = ZoneInfo("America/New_York")
    batch = []
    now = timezone.now()
    for workout in Workout.objects.all().iterator():
        if workout.completed_at:
            continue
        completed_dt = None
        if workout.completed_date:
            completed_dt = datetime.combine(
                workout.completed_date, time.min, tzinfo=ET
            )
        if workout.synced_at:
            completed_dt = workout.synced_at.astimezone(ET)
        elif workout.last_synced_at:
            completed_dt = workout.last_synced_at.astimezone(ET)
        if completed_dt is None:
            completed_dt = now.astimezone(ET)
        workout.completed_at = completed_dt
        workout.save(update_fields=["completed_at"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0019_workoutdetails_duration_seconds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={
                "ordering": ["-completed_date", "-completed_at", "-recorded_date"]
            },
        ),
        migrations.RemoveIndex(
            model_name="workout",
            name="workouts_wo_user_id_dc9ce1_idx",
        ),
        migrations.AddField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Exact completion timestamp (America/New_York) used for ordering multiple workouts per day",
                null=True,
            ),
        ),
        migrations.RunPython(populate_completed_at, noop),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["user", "-completed_date", "-completed_at"],
                name="workouts_wo_user_id_90fe20_idx",
            ),
        ),
    ]
