# Generated by assistant on 2026-02-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0020_alter_workout_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='peloton_created_at',
            field=models.DateTimeField(blank=True, null=True, help_text="Peloton 'created_at' timestamp converted to UTC"),
        ),
        migrations.AddField(
            model_name='workout',
            name='peloton_timezone',
            field=models.CharField(blank=True, max_length=64, null=True, help_text='Timezone string returned by Peloton for this workout (IANA timezone)'),
        ),
    ]
