# Generated by assistant on 2026-02-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0021_add_peloton_created_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, help_text="Exact completion timestamp reported by Peloton (stored in UTC). Use `peloton_timezone`/`peloton_created_at` for Peloton local info."),
        ),
    ]
