# Generated by Django 4.2.27 on 2026-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0022_alter_completed_at_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='title_override',
            field=models.CharField(blank=True, help_text='Optional per-workout title to override ride_detail.title (used for manual workouts)', max_length=500, null=True),
        ),
    ]
