# Generated by Django 6.0.1 on 2026-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(help_text="Challenge start date")),
                ("end_date", models.DateField(help_text="Challenge end date")),
                (
                    "signup_opens_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when signup opens for this challenge (optional, defaults to challenge start date)",
                        null=True,
                    ),
                ),
                (
                    "signup_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last date users can sign up (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this challenge is currently active",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this challenge is visible for signup",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("team", "Team Challenge"),
                            ("mini", "Mini Challenge"),
                            ("individual", "Individual Challenge"),
                        ],
                        default="mini",
                        max_length=20,
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated categories (cycling,running,strength,yoga)",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Challenge logo/image",
                        null=True,
                        upload_to="challenges/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracker_challenge",
                "ordering": ["start_date", "created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChallengeBonusWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("run", "Run"),
                            ("yoga", "Yoga"),
                            ("strength", "Strength"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                (
                    "peloton_url",
                    models.URLField(
                        blank=True,
                        help_text="Peloton workout URL (leave empty for 'Any 30 min+ Peloton Workout')",
                    ),
                ),
                (
                    "workout_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Workout title/description",
                        max_length=200,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=10,
                        help_text="Points awarded for completing this bonus workout",
                    ),
                ),
            ],
            options={
                "db_table": "tracker_challengebonusworkout",
                "ordering": ["challenge", "week_number"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChallengeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_kegels",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user wants to include Kegel exercises in their plan",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tracker_challengeinstance",
                "ordering": ["-started_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChallengeWeekUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "is_unlocked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this week is currently unlocked/live",
                    ),
                ),
                (
                    "unlock_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: Date when this week should automatically unlock",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tracker_challengeweekunlock",
                "ordering": ["challenge", "week_number"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChallengeWorkoutAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                        help_text="Day of week",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("run", "Run"),
                            ("yoga", "Yoga"),
                            ("strength", "Strength"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                ("peloton_url", models.URLField(help_text="Peloton workout URL")),
                (
                    "workout_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Workout title/description",
                        max_length=200,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=50,
                        help_text="Points awarded for completing this workout",
                    ),
                ),
                (
                    "alternative_group",
                    models.IntegerField(
                        blank=True,
                        help_text="Group ID for alternative workouts (same group = user chooses one)",
                        null=True,
                    ),
                ),
                (
                    "order_in_group",
                    models.IntegerField(
                        default=0, help_text="Order within alternative group"
                    ),
                ),
            ],
            options={
                "db_table": "tracker_challengeworkoutassignment",
                "ordering": [
                    "challenge",
                    "template",
                    "week_number",
                    "day_of_week",
                    "activity_type",
                    "alternative_group",
                    "order_in_group",
                ],
                "managed": False,
            },
        ),
    ]
