# Generated by Django 4.2.27 on 2026-01-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_team_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Week number (null = total score)",
                        null=True,
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(
                        default=0, help_text="Total team points for this challenge/week"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this score was calculated"
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leaderboards",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="challenges.team",
                    ),
                ),
            ],
            options={
                "db_table": "challenges_teamleaderboard",
                "ordering": ["-total_points", "team__name"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "week_number", "-total_points"],
                        name="challenges__challen_7a5030_idx",
                    )
                ],
                "unique_together": {("team", "challenge", "week_number")},
            },
        ),
    ]
