# Generated by Django 4.2.27 on 2026-01-23 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0003_teamleaderboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="max_members",
            field=models.IntegerField(
                default=999999,
                help_text="Maximum number of members per team (effectively unlimited)",
            ),
        ),
        migrations.CreateModel(
            name="TeamLeaderVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned",
                    models.BooleanField(
                        default=False,
                        help_text="Whether admin has assigned this volunteer to a team",
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team this volunteer was assigned to lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_volunteers",
                        to="challenges.team",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader_volunteers",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "challenge_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Challenge instance when user volunteered",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader_volunteer",
                        to="challenges.challengeinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_leader_volunteers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenges_teamleadervolunteer",
                "ordering": ["-volunteered_at"],
                "unique_together": {("user", "challenge")},
            },
        ),
    ]
