# Generated by Django 6.0.1 on 2026-02-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0015_add_plans_go_live_date"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeworkoutassignment',
            name='ride_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_assignments', to='workouts.ridedetail'),
        ),
    ]
