# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0016_add_ride_detail_to_challengeworkoutassignment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "managed": False,
                "ordering": ["start_date", "created_at"],
                "permissions": [("can_use_challenges", "Can use Challenges")],
            },
        ),
    ]
