# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0017_alter_challenge_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={"managed": False, "ordering": ["start_date", "created_at"]},
        ),
    ]
