# Generated by Django 4.2.27 on 2026-01-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_weeklyplan_completed_at_program_weeklyplan_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplanitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="points_earned",
            field=models.IntegerField(default=10),
        ),
    ]
