# Generated by Django 4.2.27 on 2026-01-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_dailyplanitem_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplanitem",
            name="ride_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="run_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="strength_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="yoga_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dailyplanitem",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ]
            ),
        ),
    ]
