# Generated by Django 4.2.27 on 2026-01-21 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plans", "0003_alter_plantemplateday_day_of_week"),
        ("tracker", "0004_dailyplanitem_ride_done_dailyplanitem_run_done_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(help_text="Challenge start date")),
                ("end_date", models.DateField(help_text="Challenge end date")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this challenge is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default template for generating weekly plans",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.plantemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="tracker.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("user", "challenge")},
            },
        ),
        migrations.RemoveField(
            model_name="weeklyplan",
            name="program",
        ),
        migrations.DeleteModel(
            name="Program",
        ),
        migrations.AddField(
            model_name="weeklyplan",
            name="challenge_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_plans",
                to="tracker.challengeinstance",
            ),
        ),
    ]
