# Generated by Django 4.2.27 on 2026-01-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_challenge_challengeinstance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="categories",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated categories (cycling,running,strength,yoga)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("team", "Team Challenge"),
                    ("mini", "Mini Challenge"),
                    ("individual", "Individual Challenge"),
                ],
                default="mini",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Challenge logo/image",
                null=True,
                upload_to="challenges/",
            ),
        ),
    ]
