# Generated by Django 4.2.27 on 2026-01-21 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plantemplateday_day_of_week"),
        ("tracker", "0006_challenge_categories_challenge_challenge_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeinstance",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                help_text="User's chosen plan template for this challenge",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plans.plantemplate",
            ),
        ),
    ]
