# Generated by Django 4.2.27 on 2026-01-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_challengeinstance_selected_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_visible",
            field=models.BooleanField(
                default=True, help_text="Whether this challenge is visible for signup"
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="signup_deadline",
            field=models.DateField(
                blank=True,
                help_text="Last date users can sign up (optional)",
                null=True,
            ),
        ),
    ]
