# Generated by Django 4.2.27 on 2026-01-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plantemplateday_day_of_week"),
        ("tracker", "0008_challenge_is_visible_challenge_signup_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="available_templates",
            field=models.ManyToManyField(
                help_text="Plan templates available for this challenge. Users can choose from these when joining.",
                related_name="challenges",
                to="plans.plantemplate",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="default_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Recommended template (should be one of the available templates)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="plans.plantemplate",
            ),
        ),
    ]
