# Generated by Django 4.2.27 on 2026-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_challenge_available_templates_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={"ordering": ["start_date", "created_at"]},
        ),
        migrations.AddField(
            model_name="challenge",
            name="signup_opens_date",
            field=models.DateField(
                blank=True,
                help_text="Date when signup opens for this challenge (optional, defaults to challenge start date)",
                null=True,
            ),
        ),
    ]
