# Generated by Django 4.2.27 on 2026-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_alter_challenge_options_challenge_signup_opens_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplanitem",
            name="peloton_ride_url",
            field=models.URLField(
                blank=True, help_text="Peloton ride workout URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="peloton_run_url",
            field=models.URLField(
                blank=True, help_text="Peloton run workout URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="peloton_strength_url",
            field=models.URLField(
                blank=True, help_text="Peloton strength workout URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="peloton_yoga_url",
            field=models.URLField(
                blank=True, help_text="Peloton yoga workout URL", null=True
            ),
        ),
    ]
