# Generated by Django 4.2.27 on 2026-01-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plantemplateday_day_of_week"),
        ("tracker", "0011_dailyplanitem_peloton_ride_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeWorkoutAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                        help_text="Day of week",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("run", "Run"),
                            ("yoga", "Yoga"),
                            ("strength", "Strength"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                ("peloton_url", models.URLField(help_text="Peloton workout URL")),
                (
                    "workout_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Workout title/description",
                        max_length=200,
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_assignments",
                        to="tracker.challenge",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_assignments",
                        to="plans.plantemplate",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "challenge",
                    "template",
                    "week_number",
                    "day_of_week",
                    "activity_type",
                ],
                "unique_together": {
                    (
                        "challenge",
                        "template",
                        "week_number",
                        "day_of_week",
                        "activity_type",
                    )
                },
            },
        ),
    ]
