# Generated by Django 4.2.27 on 2026-01-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_challengeworkoutassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeWeekUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "is_unlocked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this week is currently unlocked/live",
                    ),
                ),
                (
                    "unlock_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: Date when this week should automatically unlock",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_unlocks",
                        to="tracker.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge", "week_number"],
                "unique_together": {("challenge", "week_number")},
            },
        ),
    ]
