# Generated by Django 4.2.27 on 2026-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_challengeweekunlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeinstance",
            name="include_kegels",
            field=models.BooleanField(
                default=True,
                help_text="Whether user wants to include Kegel exercises in their plan",
            ),
        ),
    ]
