# Generated by Django 4.2.27 on 2026-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_challengeinstance_include_kegels"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyplan",
            name="bonus_workout_done",
            field=models.BooleanField(
                default=False,
                help_text="Whether the bonus workout (additional ride) is completed",
            ),
        ),
        migrations.AddField(
            model_name="weeklyplan",
            name="bonus_workout_url",
            field=models.URLField(
                blank=True,
                help_text="URL for the bonus workout (any 30 min Peloton class)",
                null=True,
            ),
        ),
    ]
