# Generated by Django 6.0.1 on 2026-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_weeklyplan_bonus_workout_done_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challengeinstance",
            unique_together=set(),
        ),
    ]
