# Generated by Django 4.2.27 on 2026-01-23 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_alter_challengeinstance_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeBonusWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField(help_text="Week number (1-based)")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("run", "Run"),
                            ("yoga", "Yoga"),
                            ("strength", "Strength"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                ("peloton_url", models.URLField(help_text="Peloton workout URL")),
                (
                    "workout_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Workout title/description",
                        max_length=200,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        default=50,
                        help_text="Points awarded for completing this bonus workout",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_workouts",
                        to="tracker.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge", "week_number"],
                "unique_together": {("challenge", "week_number")},
            },
        ),
    ]
