# Generated by Django 4.2.27 on 2026-01-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_plantemplateday_day_of_week"),
        ("tracker", "0017_add_challenge_bonus_workout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challengeworkoutassignment",
            options={
                "ordering": [
                    "challenge",
                    "template",
                    "week_number",
                    "day_of_week",
                    "activity_type",
                    "alternative_group",
                    "order_in_group",
                ]
            },
        ),
        migrations.AlterUniqueTogether(
            name="challengeworkoutassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="challengeworkoutassignment",
            name="alternative_group",
            field=models.IntegerField(
                blank=True,
                help_text="Group ID for alternative workouts (same group = user chooses one)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="challengeworkoutassignment",
            name="order_in_group",
            field=models.IntegerField(
                default=0, help_text="Order within alternative group"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="challengeworkoutassignment",
            unique_together={
                (
                    "challenge",
                    "template",
                    "week_number",
                    "day_of_week",
                    "activity_type",
                    "alternative_group",
                    "order_in_group",
                )
            },
        ),
    ]
