# Generated by Django 4.2.27 on 2026-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_add_workout_alternatives"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeworkoutassignment",
            name="points",
            field=models.IntegerField(
                default=50, help_text="Points awarded for completing this workout"
            ),
        ),
        migrations.AddField(
            model_name="dailyplanitem",
            name="workout_points",
            field=models.IntegerField(
                default=0,
                help_text="Points awarded for completing this workout (set from challenge assignment)",
            ),
        ),
        migrations.AlterField(
            model_name="challengebonusworkout",
            name="peloton_url",
            field=models.URLField(
                blank=True,
                help_text="Peloton workout URL (leave empty for 'Any 30 min+ Peloton Workout')",
            ),
        ),
        migrations.AlterField(
            model_name="challengebonusworkout",
            name="points",
            field=models.IntegerField(
                default=10, help_text="Points awarded for completing this bonus workout"
            ),
        ),
    ]
