# Generated by Django 6.0.1 on 2026-01-23 18:55

import django.db.models.deletion
from django.db import migrations, models


def noop(apps, schema_editor):
    """No-op function for models that have been moved to challenges app"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
        ("tracker", "0019_challengeworkoutassignment_points_and_more"),
    ]

    operations = [
        # Update WeeklyPlan to point to challenges.ChallengeInstance
        migrations.AlterField(
            model_name="weeklyplan",
            name="challenge_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_plans",
                to="challenges.challengeinstance",
            ),
        ),
        # Models have been moved to challenges app, so we only update state
        # without modifying the database (challenges app manages these tables)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="challenge",
                    name="available_templates",
                ),
                migrations.RemoveField(
                    model_name="challenge",
                    name="default_template",
                ),
                migrations.RemoveField(
                    model_name="challengeinstance",
                    name="challenge",
                ),
                migrations.RemoveField(
                    model_name="challengeweekunlock",
                    name="challenge",
                ),
                migrations.RemoveField(
                    model_name="challengeworkoutassignment",
                    name="challenge",
                ),
                migrations.RemoveField(
                    model_name="challengeinstance",
                    name="selected_template",
                ),
                migrations.RemoveField(
                    model_name="challengeinstance",
                    name="user",
                ),
                migrations.AlterUniqueTogether(
                    name="challengeweekunlock",
                    unique_together=None,
                ),
                migrations.AlterUniqueTogether(
                    name="challengeworkoutassignment",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="challengeworkoutassignment",
                    name="template",
                ),
                migrations.DeleteModel(
                    name="ChallengeBonusWorkout",
                ),
                migrations.DeleteModel(
                    name="ChallengeWeekUnlock",
                ),
                migrations.DeleteModel(
                    name="Challenge",
                ),
                migrations.DeleteModel(
                    name="ChallengeInstance",
                ),
                migrations.DeleteModel(
                    name="ChallengeWorkoutAssignment",
                ),
            ],
            database_operations=[],
        ),
    ]
