# Generated by Django 6.0.1 on 2026-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0025_remove_old_include_kegels_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklyplan",
            options={
                "ordering": ["-week_start"],
                "permissions": [("can_use_tracker", "Can use Tracker")],
            },
        ),
    ]
