# Generated by Django 4.2.27 on 2026-02-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0026_alter_weeklyplan_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklyplan",
            options={"ordering": ["-week_start"]},
        ),
    ]
